In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
#!pip install rasterio
import rasterio
import xarray as xr

In [19]:
pd.set_option('display.max_columns', None)
pd.set_option("display.max_rows", None)

In [31]:
# Open the GeoTIFF
with rasterio.open("Maharashtra_O3_July2024-Dec2024.tif") as src:
    data = src.read(1)  # first band
    coords = {
        "y": src.xy(0, 0)[1] - src.res[1] * np.arange(src.height),  # latitude
        "x": src.xy(0, 0)[0] + src.res[0] * np.arange(src.width)   # longitude
    }
    o3_da = xr.DataArray(data, dims=("y","x"), coords=coords)

print(o3_da)

<xarray.DataArray (y: 103, x: 132)> Size: 109kB
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
Coordinates:
  * y        (y) float64 824B 22.04 21.98 21.91 21.85 ... 15.75 15.69 15.63
  * x        (x) float64 1kB 72.66 72.72 72.79 72.85 ... 80.71 80.77 80.83 80.9


In [23]:
import rasterio
import xarray as xr
import numpy as np

def raster_to_xarray(file):
    with rasterio.open(file) as src:
        data = src.read(1)  # first band
        # create 1D coordinates using the affine transform
        transform = src.transform
        height, width = src.height, src.width

        # x coordinates: left + pixel width * column index
        x = transform.c + np.arange(width) * transform.a
        # y coordinates: top + pixel height * row index (note: transform.e is usually negative)
        y = transform.f + np.arange(height) * transform.e

        da = xr.DataArray(data, dims=("y","x"), coords={"y": y, "x": x})
    return da

uv_aerosol_da = raster_to_xarray("Maharashtra_UV_Aerosol_July2024-Dec2024.tif")
o3_da = raster_to_xarray("Maharashtra_O3_July2024-Dec2024.tif")

print(uv_aerosol_da)
print(o3_da)


<xarray.DataArray (y: 103, x: 132)> Size: 109kB
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
Coordinates:
  * y        (y) float64 824B 22.07 22.01 21.95 21.88 ... 15.78 15.72 15.66
  * x        (x) float64 1kB 72.63 72.69 72.75 72.82 ... 80.68 80.74 80.8 80.87
<xarray.DataArray (y: 103, x: 132)> Size: 109kB
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
Coordinates:
  * y        (y) float64 824B 22.07 22.01 21.95 21.88 ... 15.78 15.72 15.66
  * x        (x) float64 1kB 72.63 72.69 72.75 72.82 ... 80.68 80.74 80.8 80.87


In [30]:
import numpy as np
import xarray as xr
import pandas as pd

# o3_da = 7 km raster
# uv_aerosol_da = 500 m raster (already fine resolution)

# Compute replication factor (roughly 7km / 500m)
rep_factor_y = int(round(uv_aerosol_da.sizes["y"] / o3_da.sizes["y"]))
rep_factor_x = int(round(uv_aerosol_da.sizes["x"] / o3_da.sizes["x"]))

# Replicate O3 values to match 500 m grid
o3_rep = np.repeat(np.repeat(o3_da.values, rep_factor_y, axis=0), rep_factor_x, axis=1)

# Crop or pad if necessary to match UV shape exactly
o3_rep = o3_rep[:uv_aerosol_da.sizes["y"], :uv_aerosol_da.sizes["x"]]

# Make DataArray aligned with UV/Aerosol coordinates
o3_500m_da = xr.DataArray(o3_rep, dims=("y", "x"), coords={"y": uv_aerosol_da.y, "x": uv_aerosol_da.x})

# Combine both into a single DataFrame
xx, yy = np.meshgrid(uv_aerosol_da.x.values, uv_aerosol_da.y.values)
df = pd.DataFrame({
    "x": xx.ravel(),
    "y": yy.ravel(),
    "UV_Aerosol": uv_aerosol_da.values.ravel(),
    "O3_500m": o3_500m_da.values.ravel()
})

df.head(100)


x          y  UV_Aerosol  O3_500m
0   72.628791  22.071607         NaN      NaN
1   72.691673  22.071607         NaN      NaN
2   72.754555  22.071607         NaN      NaN
3   72.817437  22.071607         NaN      NaN
4   72.880319  22.071607         NaN      NaN
5   72.943201  22.071607         NaN      NaN
6   73.006083  22.071607         NaN      NaN
7   73.068965  22.071607         NaN      NaN
8   73.131847  22.071607         NaN      NaN
9   73.194729  22.071607         NaN      NaN
10  73.257611  22.071607         NaN      NaN
11  73.320493  22.071607         NaN      NaN
12  73.383376  22.071607         NaN      NaN
13  73.446258  22.071607         NaN      NaN
14  73.509140  22.071607         NaN      NaN
15  73.572022  22.071607         NaN      NaN
16  73.634904  22.071607         NaN      NaN
17  73.697786  22.071607         NaN      NaN
18  73.760668  22.071607         NaN      NaN
19  73.823550  22.071607         NaN      NaN
20  73.886432  22.071607         NaN      NaN
21  73.949314  22.071607         NaN      NaN
22  74.012196  22.071607         NaN      NaN
23  74.075078  22.071607         NaN      NaN
24  74.137960  22.071607         NaN      NaN
25  74.200842  22.071607         NaN      NaN
26  74.263725  22.071607         NaN      NaN
27  74.326607  22.071607   -0.459732  0.12379
28  74.389489  22.071607   -0.382672  0.12390
29  74.452371  22.071607         NaN      NaN
30  74.515253  22.071607         NaN      NaN
31  74.578135  22.071607         NaN      NaN
32  74.641017  22.071607         NaN      NaN
33  74.703899  22.071607         NaN      NaN
34  74.766781  22.071607         NaN      NaN
35  74.829663  22.071607         NaN      NaN
36  74.892545  22.071607         NaN      NaN
37  74.955427  22.071607         NaN      NaN
38  75.018309  22.071607         NaN      NaN
39  75.081191  22.071607         NaN      NaN
40  75.144074  22.071607         NaN      NaN
41  75.206956  22.071607         NaN      NaN
42  75.269838  22.071607         NaN      NaN
43  75.332720  22.071607         NaN      NaN
44  75.395602  22.071607         NaN      NaN
45  75.458484  22.071607         NaN      NaN
46  75.521366  22.071607         NaN      NaN
47  75.584248  22.071607         NaN      NaN
48  75.647130  22.071607         NaN      NaN
49  75.710012  22.071607         NaN      NaN
50  75.772894  22.071607         NaN      NaN
51  75.835776  22.071607         NaN      NaN
52  75.898658  22.071607         NaN      NaN
53  75.961540  22.071607         NaN      NaN
54  76.024422  22.071607         NaN      NaN
55  76.087305  22.071607         NaN      NaN
56  76.150187  22.071607         NaN      NaN
57  76.213069  22.071607         NaN      NaN
58  76.275951  22.071607         NaN      NaN
59  76.338833  22.071607         NaN      NaN
60  76.401715  22.071607         NaN      NaN
61  76.464597  22.071607         NaN      NaN
62  76.527479  22.071607         NaN      NaN
63  76.590361  22.071607         NaN      NaN
64  76.653243  22.071607         NaN      NaN
65  76.716125  22.071607         NaN      NaN
66  76.779007  22.071607         NaN      NaN
67  76.841889  22.071607         NaN      NaN
68  76.904771  22.071607         NaN      NaN
69  76.967654  22.071607         NaN      NaN
70  77.030536  22.071607         NaN      NaN
71  77.093418  22.071607         NaN      NaN
72  77.156300  22.071607         NaN      NaN
73  77.219182  22.071607         NaN      NaN
74  77.282064  22.071607         NaN      NaN
75  77.344946  22.071607         NaN      NaN
76  77.407828  22.071607         NaN      NaN
77  77.470710  22.071607         NaN      NaN
78  77.533592  22.071607         NaN      NaN
79  77.596474  22.071607         NaN      NaN
80  77.659356  22.071607         NaN      NaN
81  77.722238  22.071607         NaN      NaN
82  77.785120  22.071607         NaN      NaN
83  77.848003  22.071607         NaN      NaN
84  77.910885  22.071607         NaN      NaN
85  77.973767  22.071607         NaN      NaN
86  78.036

In [32]:
df = pd.DataFrame({
    "longitude": np.repeat(o3_da.x.values, o3_da.y.size),
    "latitude": np.tile(o3_da.y.values, o3_da.x.size),
    "O3": o3_da.values.flatten()
})
#df = df.dropna().reset_index(drop=True)
df.head(100)

longitude   latitude       O3
0   72.660232  22.040165      NaN
1   72.660232  21.977283      NaN
2   72.660232  21.914401      NaN
3   72.660232  21.851519      NaN
4   72.660232  21.788637      NaN
5   72.660232  21.725755      NaN
6   72.660232  21.662873      NaN
7   72.660232  21.599991      NaN
8   72.660232  21.537109      NaN
9   72.660232  21.474227      NaN
10  72.660232  21.411345      NaN
11  72.660232  21.348463      NaN
12  72.660232  21.285581      NaN
13  72.660232  21.222699      NaN
14  72.660232  21.159817      NaN
15  72.660232  21.096934      NaN
16  72.660232  21.034052      NaN
17  72.660232  20.971170      NaN
18  72.660232  20.908288      NaN
19  72.660232  20.845406      NaN
20  72.660232  20.782524      NaN
21  72.660232  20.719642      NaN
22  72.660232  20.656760      NaN
23  72.660232  20.593878      NaN
24  72.660232  20.530996      NaN
25  72.660232  20.468114      NaN
26  72.660232  20.405232      NaN
27  72.660232  20.342350  0.12379
28  72.660232  20.279468  0.12390
29  72.660232  20.216585      NaN
30  72.660232  20.153703      NaN
31  72.660232  20.090821      NaN
32  72.660232  20.027939      NaN
33  72.660232  19.965057      NaN
34  72.660232  19.902175      NaN
35  72.660232  19.839293      NaN
36  72.660232  19.776411      NaN
37  72.660232  19.713529      NaN
38  72.660232  19.650647      NaN
39  72.660232  19.587765      NaN
40  72.660232  19.524883      NaN
41  72.660232  19.462001      NaN
42  72.660232  19.399119      NaN
43  72.660232  19.336236      NaN
44  72.660232  19.273354      NaN
45  72.660232  19.210472      NaN
46  72.660232  19.147590      NaN
47  72.660232  19.084708      NaN
48  72.660232  19.021826      NaN
49  72.660232  18.958944      NaN
50  72.660232  18.896062      NaN
51  72.660232  18.833180      NaN
52  72.660232  18.770298      NaN
53  72.660232  18.707416      NaN
54  72.660232  18.644534      NaN
55  72.660232  18.581652      NaN
56  72.660232  18.518770      NaN
57  72.660232  18.455888      NaN
58  72.660232  18.393005      NaN
59  72.660232  18.330123      NaN
60  72.660232  18.267241      NaN
61  72.660232  18.204359      NaN
62  72.660232  18.141477      NaN
63  72.660232  18.078595      NaN
64  72.660232  18.015713      NaN
65  72.660232  17.952831      NaN
66  72.660232  17.889949      NaN
67  72.660232  17.827067      NaN
68  72.660232  17.764185      NaN
69  72.660232  17.701303      NaN
70  72.660232  17.638421      NaN
71  72.660232  17.575539      NaN
72  72.660232  17.512656      NaN
73  72.660232  17.449774      NaN
74  72.660232  17.386892      NaN
75  72.660232  17.324010      NaN
76  72.660232  17.261128      NaN
77  72.660232  17.198246      NaN
78  72.660232  17.135364      NaN
79  72.660232  17.072482      NaN
80  72.660232  17.009600      NaN
81  72.660232  16.946718      NaN
82  72.660232  16.883836      NaN
83  72.660232  16.820954      NaN
84  72.660232  16.758072      NaN
85  72.660232  16.695190      NaN
86  72.660232  16.632307      NaN
87  72.660232  16.569425      NaN
88  72.660232  16.506543      NaN
89  72.660232  16.443661      NaN
90  72.660232  16.380779      NaN
91  72.660232  16.317897      NaN
92  72.660232  16.255015      NaN
93  72.660232  16.192133      NaN
94  72.660232  16.129251      NaN
95  72.660232  16.066369      NaN
96  72.660232  16.003487      NaN
97  72.660232  15.940605      NaN
98  72.660232  15.877723      NaN
99  72.660232  15.814841      NaN

In [34]:
import matplotlib.pyplot as plt
import numpy as np

# Drop NaNs first
df_clean = df.dropna(subset=["O3"])

# Reshape O3 values back into a 2D grid
o3_grid = df_clean["O3"].values.reshape(o3_da.y.size, o3_da.x.size)

# Plot
plt.figure(figsize=(10,7))
plt.pcolormesh(o3_da.x.values, o3_da.y.values, o3_grid, shading='auto', cmap='viridis')
plt.colorbar(label='O3')
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.title('Spatial Distribution of O3')
plt.show()


ValueError: cannot reshape array of size 7069 into shape (103,132)

In [18]:
df.shape

(7069, 3)

In [39]:
#!pip install rasterio

import rasterio
import pandas as pd
import numpy as np
import os

# Path to the TIFF file
tiff_path = r"D:\satellite Downscaling Mini Project\Satellite-Downscaling-TE-Project\Keigan O3\Maharashtra_O3_July2024-Dec2024.tif"

# Output CSV path
csv_path = r"D:\Satellite Downscaling Mini Project\Satellite-Downscaling-TE-Project\Keigan O3\Maharashtra_O3_July2024-Dec2024.csv"

with rasterio.open(tiff_path) as src:
    data = src.read()  # shape = (bands, rows, cols)

    # Get pixel coordinates
    rows, cols = np.meshgrid(
        np.arange(data.shape[1]),
        np.arange(data.shape[2]),
        indexing='ij'
    )

    # Convert pixel indices to lat/lon
    xs, ys = rasterio.transform.xy(src.transform, rows.flatten(), cols.flatten())
    df = pd.DataFrame({"x": xs, "y": ys})

    # Add each band as a column
    for i in range(data.shape[0]):
        df[f"band_{i+1}"] = data[i].flatten()

# Save DataFrame to CSV
df.to_csv(csv_path, index=False)
print(f"Saved CSV: {csv_path}")
print(df.head())

RasterioIOError: 'D:\satellite Downscaling Mini Project\Satellite-Downscaling-TE-Project\Keigan O3\Maharashtra_O3_July2024-Dec2024.tif' not recognized as being in a supported file format.